services:
  postgres:
    image: postgres:17
    container_name: pgstmt
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: expasswd
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8 -A scram-sha-256"
      TZ: Asia/Tokyo
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 1s
      timeout: 5s
      retries: 10
  mysql:
    image: mysql:8.4
    container_name: mysqlstmt
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: expasswd
      MYSQL_DATABASE: stmtdb
      TZ: Asia/Tokyo
    healthcheck:
      test: "MYSQL_PWD=$$MYSQL_ROOT_PASSWORD mysql $$MYSQL_DATABASE -e 'SELECT 1' || exit 1"
      interval: 1s
      timeout: 5s
      retries: 50
