services:
  postgres:
    image: postgres:17
    container_name: pg2pc
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: expasswd
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8"
      TZ: Asia/Tokyo
    command: postgres -c max_prepared_transactions=1 -c log_statement=all
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 1s
      timeout: 5s
      retries: 10
  mysql:
    image: mysql:8.4
    container_name: mysql2pc
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: expasswd
      MYSQL_DATABASE: xadb
      TZ: Asia/Tokyo
    command: mysqld --general_log=on --general_log_file=/var/lib/mysql/query.log --log_timestamps=SYSTEM
    healthcheck:
      test: "MYSQL_PWD=expasswd mysql xadb -e 'SELECT 1' || exit 1"
      interval: 2s
      timeout: 5s
      retries: 50
